### ISSUE TITLE
Not an "issue" per se, but clucumber does not seem to be available via quicklisp (anymore?)

### ISSUE THREAD

**Issue by danomeerf** [antifuchs/clucumber#2]
Subject says all...

**Comment by antifuchs** [comment]
Yep! This is mostly by design - it's not terribly useful without hooking into cucumber, which is a ruby gem. The best way to install clucumber (though I haven't tried it with recent versions of cucumber) is to put it in a [bundler](http://bundler.io/) Gemfile together with cucumber and use rubygems to install both of them.
